### ISSUE TITLE
Problème pour une image bmp

### ISSUE THREAD

**Issue by MaxenceDeCreus** [MaxenceGrenot/bmpfilter#13]
Bonjour, il y a un problème, je n'arrive pas à mettre mon image bmp, voici le lien : http://icn.lycee-valin.fr/projets2017/seconde13/eleve13/images/imaget.bmp
Merci de régler ce problème.

**Comment by nyan42** [comment]
Bonjour Maxence,
Le fichier bmp que tu utilises est du style bmp 32, sauf que notre application ne peut qu'utiliser du bmp 24.
Tu retrouveras toutes les informations dans le README.md.
Je clôture donc ce ticket.
